# Generated by Django 3.2.9 on 2021-12-06 15:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211118_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe',
            field=tinymce.models.HTMLField(default='Here goes the Recipe'),
        ),
    ]
